### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by antonrejoe** [react-appwrite/react-appwrite#39]
**Additional info :**

```BASH

$ uname -a

Output :
Linux Sekiro 6.2.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000 x86_64 GNU/Linux

```

### The error message goes this way

```BASH
error - node_modules/appwrite/dist/esm/sdk.js (245:0) @ Client.setEndpoint
error - TypeError: Cannot read properties of undefined (reading 'replace')
    at eval (./app/layout.tsx:14:69)
    at (sc_client)/./app/layout.tsx (/run/media/antonrejoe/ssd_internal_victus/mcj@victus/react-appwrite.org/react-appwrite/react-appwrite/example/.next/server/app/page.js:739:1)
    at __webpack_require__ (/run/media/antonrejoe/ssd_internal_victus/mcj@victus/react-appwrite.org/react-appwrite/react-appwrite/example/.next/server/webpack-runtime.js:33:43)
null
error - node_modules/appwrite/dist/esm/sdk.js (245:0) @ Client.setEndpoint
error - TypeError: Cannot read properties of undefined (reading 'replace')
    at eval (./app/layout.tsx:14:69)
    at (sc_client)/./app/layout.tsx (/run/media/antonrejoe/ssd_internal_victus/mcj@victus/react-appwrite.org/react-appwrite/react-appwrite/example/.next/server/app/page.js:739:1)
    at __webpack_require__ (/run/media/antonrejoe/ssd_internal_victus/mcj@victus/react-appwrite.org/react-appwrite/react-appwrite/example/.next/server/webpack-runtime.js:33:43)
null
```

**This error is being caused by the layout.tsx file  ( example/app/layout.tsx)**

```TSX

"use client";
import "./styles.css";
import type { ReactNode } from "react";
import { AppwriteProvider } from "react-appwrite";
import { Client } from "appwrite";

const appwrite = new Client();
.setEndpoint(process.env.NEXT_PUBLIC_APPWRITE_URL as string);
.setProject(process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID as string);

type Props = {
  children: ReactNode;
};

function MainLayout({ children }: Props) {
  return (
    <html
      lang="en"
      style={{
        background: "black",
      }}
    >
      <head />

      <body>
        <main>
          <AppwriteProvider devTools client={appwrite}>
            {children}
          </AppwriteProvider>
        </main>
      </body>
    </html>
  );
}

export default MainLayout;
```

**Comment by sanny-io** [comment]
What version of Appwrite are you using?

And do you have your Appwrite environment variables set up?

**Comment by antonrejoe** [comment]
@sanny-io  appwrite is the latest and I didn't setup env var's bro sorry for that

**Comment by antonrejoe** [comment]
@sanny-io  rn this error is coming up bro 

```BASH

SyntaxError: Expected property name or '}' in JSON at position 808
    at JSON.parse (<anonymous>)
    at patchIncorrectLockfile (/run/media/antonrejoe/ssd_internal_victus/mcj@victus/react-appwrite.org/react-appwrite/react-appwrite/example/node_modules/next/dist/lib/patch-incorrect-lockfile.js:93:33)
SyntaxError: Expected property name or '}' in JSON at position 808
    at JSON.parse (<anonymous>)
    at patchIncorrectLockfile (/run/media/antonrejoe/ssd_internal_victus/mcj@victus/react-appwrite.org/react-appwrite/react-appwrite/example/node_modules/next/dist/lib/patch-incorrect-lockfile.js:93:33)

```

**Comment by antonrejoe** [comment]
@sanny-io ok bruh give me some time , I'll do it ASAP

**Comment by antonrejoe** [comment]
![image](https://user-images.githubusercontent.com/89238559/234245819-ec302a80-a227-4c23-b640-dfbe73c689d5.png)
and
![image](https://user-images.githubusercontent.com/89238559/234245997-da9784b8-44ce-4179-b1ab-bfd39b1e521a.png)

**Comment by antonrejoe** [comment]
@sanny-io  now things started working properly magically Idk

**Comment by sanny-io** [comment]
Good to hear 🙂
